version: '3.8'

services:
  kafka1:
    image: vinsdocker/kafka
    container_name: kafka
    ports:
    - "9092:9092"
    environment:
      KAFKA_CLUSTER_ID: OTMwNzFhYTY1ODNiNGE5OT
    volumes:
    - ./props/server.properties:/kafka/config/kraft/server.properties
    - ./data:/tmp/kafka-logs

  postgres:
    image: postgres
    container_name: postgres-local
    environment:
      POSTGRES_USER: kynpostgres
      POSTGRES_PASSWORD: kynpostgrespw
      POSTGRES_DB: kynpost
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network

  redis:
    image: redis
    container_name: redis-local
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - app-network

  mongo:
    image: mongo
    container_name: mongo-local
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: kynmongo
      MONGO_INITDB_ROOT_PASSWORD: kynmongopw
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

volumes:
  kafka-data: 
  postgres-data:
  redis-data:
  mongo-data:

networks:
  app-network:
    driver: bridge