package com.kyn.order.common.enums;

public enum WorkflowAction {

    PAYMENT_REQUEST_INITIATED,
    PAYMENT_PROCESSED,
    PAYMENT_DECLINED,
    PAYMENT_REFUND_INITIATED,

    INVENTORY_REQUEST_INITIATED,
    INVENTORY_DEDUCTED,
    INVENTORY_DECLINED,
    INVENTORY_RESTORE_INITIATED,


}
