spring:
  cloud:
    function:
      definition: orderOrchestrator;messageEventSupplier;MessageConsumer
    stream:
      default:
        producer:
          useNativeEncoding: true
      bindings:
        orderOrchestrator-in-0:
          destination: payment-response,inventory-response
          group: order-service-group
        payment-request-channel:
          destination: payment-request
        inventory-request-channel:
          destination: inventory-request
        messageEventSupplier-out-0:
          destination: message-request-channel
          group: message-service-group
        MessageConsumer-in-0:
          destination: message-request-channel
          group: message-service-group
      kafka:
        binder:
          consumer-properties:
            "value.deserializer": org.springframework.kafka.support.serializer.JsonDeserializer
            "key.deserializer": org.apache.kafka.common.serialization.StringDeserializer
            "auto.offset.reset": "earliest"
            "spring.json.trusted.packages": "com.kyn.common.messages.*"
          producer-properties:
            "value.serializer": org.springframework.kafka.support.serializer.JsonSerializer
            "key.serializer": org.apache.kafka.common.serialization.StringSerializer
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/kynpost
    username: kynpostgres
    password: kynpostgrespw
