spring:
  application:
    name: inventory-service
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/kynpost
    username: kynpostgres
    password: kynpostgrespw
  sql:
    init:
      mode: always
  cloud:
    function:
      definition: processor
    stream:
      default:
        producer:
          useNativeEncoding: true
      bindings:
        processor-in-0:
          destination: cart-inventory-request
          group: inventory-service-group
        processor-out-0:
          destination: cart-inventory-response
      kafka:
        binder:
          consumer-properties:
            "value.deserializer": org.springframework.kafka.support.serializer.JsonDeserializer
            "key.deserializer": org.apache.kafka.common.serialization.StringDeserializer
            "auto.offset.reset": "earliest"
            "spring.json.trusted.packages": "com.kyn.common.messages.*"
          producer-properties:
            "value.serializer": org.springframework.kafka.support.serializer.JsonSerializer
            "key.serializer": org.apache.kafka.common.serialization.StringSerializer
        brokers: localhost:9092
        consumer:
            configuration:
              heartbeat.interval.ms: 3000
              session.timeout.ms: 600000
              max.poll.interval.ms: 300000
              request.timeout.ms: 605000

server:
  port: 8084
